#!/bin/sh
#
# Copyright (c) 2017 DornerWorks
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

EXTFS_MNT="/extendedfs-overlay"
OVERLAY_DIR=$EXTFS_MNT/overlay
OVERLAY_WORK=$EXTFS_MNT/work

EXTFS_DEV="/dev/mmcblk0p2"
if [ -b "/dev/xvda2" ]; then
    EXTFS_DEV="/dev/xvda2"
fi

do_start()
{
    if [ ! -b "$EXTFS_DEV" ]; then
        echo "No overlay partition found."
        exit 1
    fi

    echo "Creating Overlay Mountpoints"
    mkdir $EXTFS_MNT

    echo "Mounting Overlay Devices"
    echo "$EXTFS_DEV to $EXTFS_MNT"
    mount $EXTFS_DEV $EXTFS_MNT

    ${OVERLAY_DIR}/usr/bin/set_hostname.sh
    for i in $(find $OVERLAY_DIR -maxdepth 1 -mindepth 1 -type d); do
        BASE_DIR=`basename $i`
        WORK_DIR=${OVERLAY_WORK}/${BASE_DIR}-work

        if [ ! -d "$BASE_DIR" ]; then
            mkdir $BASE_DIR
        fi

        if [ ! -d "$WORK_DIR" ]; then
            mkdir -p $WORK_DIR
        fi

        echo "Mount $i over $BASE_DIR using $WORK_DIR"
        mount -t overlay overlay \
              -olowerdir=$BASE_DIR,upperdir=$i,workdir=$WORK_DIR \
              $BASE_DIR

        if [ $? -ne 0 ]; then
            rm -rf $WORK_DIR
        fi
    done
}

do_stop()
{
    if [ ! -b "$EXTFS_DEV" ]; then
        echo "No overlay partition found."
        exit 1
    fi

    echo "Tearing Down Overlay"

    for i in $(find $OVERLAY_DIR -maxdepth 1 -mindepth 1 -type d); do
        BASE_DIR=`basename $i`
        WORK_DIR=${OVERLAY_WORK}/${BASE_DIR}-work

        echo "Unmounting $i from $BASE_DIR"

        if [ -d "$WORK_DIR" ]; then
            umount $BASE_DIR
            rm -rf $WORK_DIR
        fi
    done

    umount $EXTFS_MNT
    rm -rf $EXTFS_MNT
}

case "$1" in
    start)
	     do_start
	     ;;
    status)
	     test -d "$EXTFS_MNT"
        ;;
    stop)
        do_stop
	     ;;
    restart)
        do_stop
        do_start
        ;;
    *)
	     echo $"Usage: $0 {start|stop|status|restart}"
	     false
esac

exit $?
