#!/bin/sh
#
# Copyright (c) 2017 DornerWorks
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

do_start()
{
    if [ -f /proc/xen/capabilities ] && \
           grep -q "control_d" /proc/xen/capabilities ; then
        # On Xen.  Bring up the bridge.
        ifup xenbr0
    else
        # Not on Xen.  Get a DHCP address for eth0.
        udhcpc -i eth0 -b
    fi
}

do_stop()
{
    if [ -f /proc/xen/capabilities ] && \
           grep -q "control_d" /proc/xen/capabilities ; then
        # On Xen.  Bring down the bridge.
        ifdown xenbr0
    fi
}

do_restart()
{
    if [ -f /proc/xen/capabilities ] && \
           grep -q "control_d" /proc/xen/capabilities ; then
        # On Xen.  Restart the bridge.
        ifdown xenbr0
        ifup xenbr0
    fi
}

case "$1" in
    start)
	     do_start
	     ;;
    status)
	     ifconfig | grep -q xenbr0
        ;;
    stop)
        do_stop
	     ;;
    restart)
        do_stop
        do_start
        ;;
    *)
	     echo $"Usage: $0 {start|stop|status|restart}"
	     false
esac

exit $?
